// import { BookText, CodeSquare, HomeIcon, UserRound, Linkedin, Twitter, Rss, Twitch, Youtube, Crop, Pencil, Computer, Book, Rocket, Speech } from "lucide-react";
// import  Prototipo0 from "./src/assets/images/Prototipo0.png"
// import imageToAdd from "./../assets/images/logo.png";

export const ProjectsCards = [
    {
        id: 1,
        srcImg: 'https://workana.s3.amazonaws.com/portfolios/cl/596d8f16e8df03bdb30b008995b40b93/Prototipo0.png?response-content-disposition=inline%3Bfilename%3D%22Prototipo0.png%22&response-content-type=image%2Fpng&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA33COQEVTJSIXHA73%2F20240902%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240902T230802Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Signature=d2c803df5e3ce77e126edc71e0d490d7ef5dedd594a463605b19b88addce9756',
        title: "Prototipo 1",
        skill1: "PCB Desing",
        skill2: "PCB Desing",
        skill3: "PCB Desing",
        skill4: "PCB Desing",
        skill5: "PCB Desing",
        src: "https://www.instagram.com/brian__2564/",
    },
    {
        id: 2,
        // logo: <Linkedin size={30} strokeWidth={1} />,
        title: "Prototipo 2",
        skill1: "PCB Desing",
        skill2: "PCB Desing",
        skill3: "PCB Desing",
        skill4: "PCB Desing",
        skill5: "PCB Desing",
        src: "https://www.linkedin.com/in/brianregalado/",
    },
    {
        id: 3,
        // logo: <Twitter size={30} strokeWidth={1} />,
        title: "Prototipo 3",
        skill1: "PCB Desing",
        skill2: "PCB Desing",
        skill3: "PCB Desing",
        skill4: "PCB Desing",
        skill5: "PCB Desing",
        src: "https://x.com/BrianRegalado18",
    },
    {
        id: 4,
        // logo: <Rss size={30} strokeWidth={1} />,
        title: "Prototipo 4",
        skill1: "PCB Desing",
        skill2: "PCB Desing",
        skill3: "PCB Desing",
        skill4: "PCB Desing",
        skill5: "PCB Desing",
        src: "#!",
    },
    {
        id: 4,
        // logo: <Twitch size={30} strokeWidth={1} />,
        title: "Prototipo 5",
        skill1: "PCB Desing",
        skill2: "PCB Desing",
        skill3: "PCB Desing",
        skill4: "PCB Desing",
        skill5: "PCB Desing",
        src: "https://www.twitch.tv/trueno2564",
    },
];