// import { BookText, CodeSquare, HomeIcon, UserRound, Linkedin, Twitter, Rss, Twitch, Youtube, Crop, Pencil, Computer, Book, Rocket, Speech } from "lucide-react";
// import  Prototipo0 from "./src/assets/images/Prototipo0.png"
// import imageToAdd from "./../assets/images/logo.png";

export const ProjectsCards = [
    {
        id: 1,
        srcImg: 'https://raw.githubusercontent.com/Trueno2564/nextjs-rating-cards/master/src/assets/images/NAS_5.bmp',
        title: "Prototipo NAS",
        skill1: "PCB Desing",
        skill2: "Electronica",
        skill3: "3D Desing",
        skill4: "Altium Designer",
        skill5: "Inventor",
        src: "https://www.instagram.com/brian__2564/",
    },
    {
        id: 2,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/Brazo%20rob%C3%B3tico2.png?raw=true',
        title: "Brazo Robotico",
        skill1: "PCB Desing",
        skill2: "Inventor",
        skill3: "Electronica",
        skill4: "Arduino",
        skill5: "Diseño y Fabricacion",
        src: "https://www.linkedin.com/in/brianregalado/",
    },
    {
        id: 3,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/PERIPHERAL_4.png?raw=true',
        title: "Proyecto Privado",
        skill1: "PCB Desing",
        skill2: "Altium Designer",
        skill3: "KiCad",
        skill4: "Electronica",
        skill5: "Diseño y Fabricacion",
        src: "https://x.com/BrianRegalado18",
    },
    {
        id: 4,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/Cabina_1.png?raw=true',
        title: "Bus Control Board",
        skill1: "PCB Desing",
        skill2: "Altium Designer",
        skill3: "KiCad",
        skill4: "Electronica",
        skill5: "Diseño y Fabricacion",
        src: "#!",
    },
    {
        id: 5,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/CNC.png?raw=true',
        title: "Mini Maquina CNC",
        skill1: "3D Desing",
        skill2: "Inventor",
        skill3: "Electronica",
        skill4: "Arduino",
        skill5: "Diseño y Fabricacion",
        src: "https://www.twitch.tv/trueno2564",
    },
    {
        id: 6,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/pasarela_1.png?raw=true',
        title: "Pasarela ESP32",
        skill1: "PCB Desing",
        skill2: "Altium Designer",
        skill3: "KiCad",
        skill4: "Electronica",
        skill5: "Diseño y Fabricacion",
        src: "https://www.twitch.tv/trueno2564",
    },
    {
        id: 7,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/CENTRALITA_1.png?raw=true',
        title: "Prototipo Centralita",
        skill1: "PCB Desing",
        skill2: "Altium Designer",
        skill3: "KiCad",
        skill4: "Electronica",
        skill5: "Diseño y Fabricacion",
        src: "https://www.twitch.tv/trueno2564",
    },
    {
        id: 8,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/Sermax_1.png?raw=true',
        title: "Headers Control",
        skill1: "PCB Desing",
        skill2: "Altium Designer",
        skill3: "KiCad",
        skill4: "Electronica",
        skill5: "Diseño y Fabricacion",
        src: "https://www.twitch.tv/trueno2564",
    },
    {
        id: 9,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/Kit_Arduino_3.png?raw=true',
        title: "Kit Arduino",
        skill1: "PCB Desing",
        skill2: "Altium Designer",
        skill3: "3D Desing",
        skill4: "Electronica",
        skill5: "Arduino",
        src: "https://www.twitch.tv/trueno2564",
    },
    {
        id: 10,
        srcImg: 'https://github.com/Trueno2564/nextjs-rating-cards/blob/master/src/assets/images/servos.png?raw=true',
        title: "Control Servos",
        skill1: "PCB Desing",
        skill2: "Fusion 360",
        skill3: "KiCad",
        skill4: "Electronica",
        skill5: "Arduino",
        src: "https://www.twitch.tv/trueno2564",
    },
];